default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: post_development

test:
  <<: *default
  database: post_test

production:
  <<: *default
  database: post_production
  username: post
  password: <%= ENV['POST_DATABASE_PASSWORD'] %>
